import type { Internship, StudentProfile } from './types';

export const mockInternships: Internship[] = [
  {
    id: '1',
    title: 'Frontend Developer Intern',
    company: 'Innovate Inc.',
    logo: 'https://placehold.co/100x100.png',
    location: 'Remote',
    domain: 'Web Development',
    stipend: '$2000/month',
    duration: '3 Months',
    postedDate: '2 Weeks Ago',
    applicants: 125,
    description: 'Join our team to build beautiful and responsive user interfaces for our next-generation web applications. You will work with React, Next.js, and Tailwind CSS.',
    responsibilities: [
      'Develop new user-facing features',
      'Build reusable code and libraries for future use',
      'Ensure the technical feasibility of UI/UX designs',
      'Optimize application for maximum speed and scalability',
    ],
    skills: ['React', 'Next.js', 'Tailwind CSS', 'TypeScript', 'Git'],
    perks: ['Flexible work hours', 'Mentorship program', 'Letter of recommendation'],
  },
  {
    id: '2',
    title: 'UX/UI Design Intern',
    company: 'Creative Solutions',
    logo: 'https://placehold.co/100x100.png',
    location: 'New York, NY',
    domain: 'Design',
    stipend: '$1800/month',
    duration: '2 Months',
    postedDate: '1 Week Ago',
    applicants: 88,
    description: 'We are looking for a creative UX/UI intern to help design intuitive and engaging user experiences. You will be involved in the entire design process from wireframing to final mockups.',
    responsibilities: [
      'Conduct user research and evaluate user feedback',
      'Create user flows, wireframes, prototypes, and mockups',
      'Collaborate with product managers and engineers',
      'Uphold and contribute to our design system',
    ],
    skills: ['Figma', 'Sketch', 'Adobe XD', 'User Research', 'Prototyping'],
    perks: ['Paid relocation', 'Free lunch', 'Company merch'],
  },
  {
    id: '3',
    title: 'Backend Developer Intern',
    company: 'DataStream',
    logo: 'https://placehold.co/100x100.png',
    location: 'San Francisco, CA',
    domain: 'Web Development',
    stipend: '$2500/month',
    duration: '4 Months',
    postedDate: '3 Days Ago',
    applicants: 210,
    description: 'Work on the core infrastructure of our data processing pipeline. You will be using Node.js, Python, and various AWS services to build scalable and reliable systems.',
    responsibilities: [
      'Design and implement RESTful APIs',
      'Work with databases like PostgreSQL and Redis',
      'Write efficient and reusable code',
      'Deploy and monitor services on AWS',
    ],
    skills: ['Node.js', 'Python', 'PostgreSQL', 'AWS', 'Docker'],
    perks: ['Health insurance', 'Stock options', 'Team outings'],
  },
  {
    id: '4',
    title: 'Digital Marketing Intern',
    company: 'Growth Gurus',
    logo: 'https://placehold.co/100x100.png',
    location: 'Remote',
    domain: 'Marketing',
    stipend: '$1500/month',
    duration: '3 Months',
    postedDate: '1 Month Ago',
    applicants: 150,
    description: 'Help us grow our online presence through various digital marketing channels. You will learn about SEO, SEM, content marketing, and social media marketing.',
    responsibilities: [
      'Assist in managing social media accounts',
      'Create content for blogs and newsletters',
      'Analyze marketing campaign performance',
      'Conduct keyword research for SEO',
    ],
    skills: ['SEO', 'Content Writing', 'Google Analytics', 'Social Media Marketing'],
    perks: ['Certificate of completion', 'Performance bonus', 'Flexible schedule'],
  },
  {
    id: '5',
    title: 'Data Science Intern',
    company: 'AI Forward',
    logo: 'https://placehold.co/100x100.png',
    location: 'Boston, MA',
    domain: 'Data Science',
    stipend: '$3000/month',
    duration: '6 Months',
    postedDate: '5 Days Ago',
    applicants: 95,
    description: 'Dive into large datasets to extract meaningful insights and build predictive models. You will be working with a team of experienced data scientists on real-world problems.',
    responsibilities: [
        'Clean and preprocess large datasets',
        'Build and train machine learning models',
        'Visualize data and present findings',
        'Collaborate with engineers to deploy models',
    ],
    skills: ['Python', 'Pandas', 'Scikit-learn', 'TensorFlow', 'SQL'],
    perks: ['Conference budget', 'Access to cutting-edge hardware', 'Publication opportunities'],
  },
  {
    id: '6',
    title: 'Product Management Intern',
    company: 'NextGen Apps',
    logo: 'https://placehold.co/100x100.png',
    location: 'Remote',
    domain: 'Product Management',
    stipend: '$2200/month',
    duration: '3 Months',
    postedDate: '10 Days Ago',
    applicants: 180,
    description: 'Learn the ropes of product management by working closely with our product and engineering teams. You will help define product features, write specifications, and analyze user data.',
    responsibilities: [
        'Conduct market and competitor analysis',
        'Gather and prioritize product requirements',
        'Work with designers to create user-friendly interfaces',
        'Track and analyze product metrics',
    ],
    skills: ['Product Sense', 'Data Analysis', 'Agile Methodologies', 'Communication'],
    perks: ['Direct impact on product', 'Mentorship from senior PMs', 'Career coaching'],
  },
];

export const mockStudentProfile: StudentProfile = {
  name: 'Alex Doe',
  email: 'alex.doe@example.com',
  education: 'B.S. in Computer Science, Stanford University (2025)',
  skills: 'React, Node.js, Python, UI/UX Design, Figma, Project Management',
  about: 'A passionate and driven computer science student with a keen interest in developing innovative software solutions. Eager to apply my skills in a challenging and growth-oriented internship environment. Proven ability to learn quickly and collaborate effectively in team settings.',
};
